defmodule Aves.Repo.Migrations.AddUserAuthFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :email, :citext, null: false
      add :nickname, :text, null: false
      add :hashed_password, :text, null: false
      add :rol, :text, null: false, default: "usuario"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:nickname], name: "users_unique_nickname_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:nickname], name: "users_unique_nickname_index")

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :rol
      remove :hashed_password
      remove :nickname
      remove :email
    end
  end
end
