site:
  title: Bitacora de Aves - Mobile
  start_page: bitacora-mobile::index.adoc
content:
  sources:
    - url: ..
      branches: HEAD
      worktrees: .
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./_build/site
asciidoc:
  attributes:
    experimental: ''
